version: '3.8'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: task_management_db
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://127.0.0.1:27017/task_management_db
      PORT: 4000
      JWT_SECRET: your_jwt_secret_key
      JWT_EXPIRES_IN: 1h
